### ISSUE TITLE
java.lang.IllegalArgumentException: shortLabel cannot be empty

### ISSUE THREAD

**Issue by Lxxyx** [madriska/react-native-quick-actions#45]
config:

```
const items = [
  {
    type: "周课表", // Required
    title: '',
    icon: 'Date', // Pass any of UIApplicationShortcutIconType<name>
    userInfo: {
      url: ''    
}
  },
  {
    type: "空闲教室",
    title: '',
    icon: 'Compose',
    userInfo: {
      url: ''   
}
  },
  {
    type: "用电查询",
    title: '',
    icon: 'Cloud',
    userInfo: {
      url: ''
    }
  }
]
```

Log

```
08-28 12:10:09.727 14044-14106/edu.ncu.ncuhome.iNCU E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
                                                                      Process: edu.ncu.ncuhome.iNCU, PID: 14044
                                                                      java.lang.IllegalArgumentException: shortLabel cannot be empty
                                                                          at com.android.internal.util.Preconditions.checkStringNotEmpty(Preconditions.java:79)
                                                                          at android.content.pm.ShortcutInfo$Builder.setShortLabel(ShortcutInfo.java:852)
                                                                          at com.reactNativeQuickActions.AppShortcutsModule.setShortcutItems(AppShortcutsModule.java:112)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:345)
                                                                          at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:136)
                                                                          at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                          at android.os.Handler.handleCallback(Handler.java:751)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                          at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                          at java.lang.Thread.run(Thread.java:761)
```

**Comment by Lxxyx** [comment]
fixed by set title not ''
